name: Andrew Dai
author: Andrew Dai
markdown: kramdown
plugins: [jekyll-gist, jekyll-paginate]
highlighter: "rouge"
permalink: none
paginate: 12
paginate_path: "blog/page:num/"

googleAnalyticsId: "UA-20508277-4"
